language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=shariff-plus-$TRAVIS_TAG

cache:
  directories:
    - node_modules

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run build_zip

deploy:
  - provider: releases
    api_key:
      secure: "H6X2U+rjwgA9ieP48oeCEGMGmXDq//GhFQctJYY8cRGSmDMfG2roOP0pPY8aK0+y5JDaQg/AI8YNBNyaqiAwiVyYiGdnnmlcyCjXE6cMxObf+1MU98ncCuZUfkK9poq7VzrjYlnT0u1pCMBzgCNUxQNxn+QXZI+RbGHxvQzsnlHAU5SjQWLqi/jB4trCjeyeYbEhI+cRoE86IqzEmVBCUGnH+7XB0P6qUOVYKh2HquUGiRFN7OZyj3o03xzaBhrBnucn5hc8QhnJ2aR+GBmFw09NMxfARGkiU81TcnsluurFi0jrRYxpQbttIHHPJ0Jn+ExzzbqeUzZA6gM8tQU3dJLUU7Z9Y6RmT9z5iQBG5bq6BTMv6r3zfata2pU7d3WDjstXVDfDrh5EC471U4Lh16wqdAgNhbYTn+fp3uuiRyDNbF7TPbwmStGYo5wMevFOYsr+c8V+hc2qdyJp44I/6abAp/Ytbo4n26hKJZitWRzklVMbpHche2fRAHFN6MdhOgjFcJGJiO4LBEmbR8TXTPia5GIMO+Ejk6m4oB/7hCYA6+R2hPcxSnz1SpQVBYi4WA2Y7diH7ahmraY/ccPhd5V3JjrG03LQFBuu+F+FyOuIW2w6PaKWjKg7vxwcJcGomhm1hs5hHb2yx9r9/YB8qevpM4NtcxlZhcPjHLsSmTw="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
  - provider: npm
    email: richard.fath@t-online.de
    api_key:
      secure: "GT4YyWJ3/FwdkeRsy52o32GyvKUYTy1TSWKXLTBrhskZ/eNSzwz+VrDJzY+oKyb4+IWw1GOJT7jXVME5UVOH72VhVCVWnbRQL4bIJQun2SjkcEeUBHDgIvtNHD5aDbFWfM5in8Upywqw1ic5QkkzlHoKChaud6p3ZGGB/7euxfojjFPN8l2mqcQi4anels0n2y2mNFo9uzTSRHAXnB8JzPs7KVRcTZsI9Vv7WXidkeOAblPUaxqMiGpYwbEcc8OOLC6f4/HLameoa10oOZWEXNqC2OYabPd39zZS43LuM1RBYXk4b58eJdG/REyg+uXx+a7FmVk7kmeIkFpBUQjEeAOJDkL9NXfCVSd+1zJYXXonV0xss7ab3dWgiZDguZcsU96zgNQ2+vMprRUm3hJ7tjlh9sXp2R34yvIo2TpfRPgYYg5TqEbQgGaY+mnTPhUcbHSDmh8/ATy+kbIi9uNYk3kY18UaS8OBttIh9bN+SmP0HLeGvYFvtghOAeKBQI64GABDsnWHdf4VLGE7QfHzoc7Zyr7v67acLo82MiPRmCZFo50WSJfkiqro4m8jfjMDf2+4a3ifP8zfCX/8AtzUfPamrNQXZGZkBs3OynttDZYNPTOVwdevqLXIJKTceTMAzT4v7OxjxzXAkr2UYOHxB2RNq/TFxbrtRKngiZx6VFY="
    skip_cleanup: true
    on:
      repo: richard67/shariff-plus
      tags: true
